import { createContext, useContext, useState, useEffect, type ReactNode } from "react";

export type Lang = "en" | "ru";

const translations = {
  en: {
    nav: { templates: "Templates", showcase: "Showcase", about: "About Project", getStarted: "Get Started", searchPlaceholder: "Search templates..." },
    hero: { badge: "Premium Templates", line1: "Crafting", line2: "Digital", line3: "Excellence.", subtitle: "High-converting landing page templates built with precision. Designed to elevate your brand.", explore: "Explore Templates", viewShowcase: "View Showcase", templateCount: "24 Templates", responsive: "Fully Responsive", updates: "Free Updates" },
    featured: { label: "Featured", title: "Top Picks" },
    collection: { label: "Collection", title: "All Templates", all: "All", noResults: "No templates found", noResultsHint: "Try selecting a different category.", clearFilters: "Clear Filters", preview: "Preview" },
    detail: {
      back: "Back to Templates", getTemplate: "Get this Template", orderPrefix: "I would like to order a website based on the template", livePreview: "Live Preview", included: "What's Included", creators: "200+ creators", creatorsDesc: "already using this template", notFound: "Template Not Found", notFoundDesc: "The template you're looking for doesn't exist or has been removed.", returnHome: "Return Home",
      features: { responsive: "Fully Responsive", responsiveDesc: "Pixel-perfect on every screen size and device.", performance: "Performance First", performanceDesc: "Optimized for speed, SEO, and conversions.", code: "Clean Code", codeDesc: "Well-structured, commented, and easy to extend.", design: "Custom Design", designDesc: "Unique, hand-crafted design with attention to detail.", browser: "Cross-Browser", browserDesc: "Tested across all modern browsers.", practices: "Best Practices", practicesDesc: "Built with accessibility and security in mind." },
    },
    footer: {
      title: "Ready to Launch?", subtitle: "Describe your project — I'll suggest structure, format and timeline. Response within 24 hours.",
      form: { name: "Name", namePlaceholder: "Your name", contact: "Contact (Telegram or Email)", contactPlaceholder: "@telegram or email", projectType: "Project Type", projectTypes: ["Landing", "Redesign", "Other"] as readonly string[], timeline: "Timeline", timelines: ["Standard", "Fast 3–5 days"] as readonly string[], description: "Short Description", descriptionPlaceholder: "Tell me about your project...", submit: "Start a Project" },
      contacts: { telegram: "Telegram", telegramDesc: "Fastest response", email: "Email", emailDesc: "For official inquiries" },
      remote: "Remote worldwide · RU / EN", rights: "FormCraft. All rights reserved.",
    },
    about: { title: "About Project", content: ["I design landing pages as strategic conversion systems.", "Every project starts with product analysis, audience psychology, and growth positioning — not visuals.", "First comes logic.\nThen structure.\nThen visual direction.\nOnly after that — impact.", "I work across styles — from refined luxury aesthetics to bold digital experiences —\nbut the foundation never changes:", "Clarity.\nAttention control.\nConversion.", "A landing page is not decoration.\nIt's a controlled interaction scenario.", "And every pixel serves a purpose."] },
    marquee: ["Landing Pages", "E-Commerce", "SaaS", "Portfolio", "Creative", "Luxury", "Interactive", "Minimal"] as readonly string[],
    categories: { "All": "All", "E-commerce": "E-commerce", "Creative": "Creative", "Luxury": "Luxury", "Personal": "Personal", "Product": "Product", "SaaS": "SaaS", "Lifestyle": "Lifestyle", "Food & Drink": "Food & Drink", "Entertainment": "Entertainment", "Business": "Business", "Fintech": "Fintech", "Media": "Media" } as Record<string, string>,
    styles: { minimal: "Minimal", brutalist: "Brutalist", luxury: "Luxury", futuristic: "Futuristic" } as Record<string, string>,
    niches: { SaaS: "SaaS", portfolio: "Portfolio", marketplace: "Marketplace", event: "Event" } as Record<string, string>,
    moods: { clean: "Clean", bold: "Bold", cinematic: "Cinematic", playful: "Playful" } as Record<string, string>,
    templateData: {
      "Nova Studio": { title: "Nova Studio", description: "Minimalist template for creative studios and designers. Clean typography, large images and modern grid." },
      "DarkMatter": { title: "DarkMatter", description: "Dark cinematic landing for digital agencies and art projects. Neon accents and smooth animations." },
      "Launchpad": { title: "Launchpad", description: "The perfect template for startups. Clear structure helps quickly communicate product value and convert visitors." },
      "Velour": { title: "Velour", description: "Elegant premium template for luxury brands and designer products. Soft palette and refined typography." },
      "Orbit": { title: "Orbit", description: "Futuristic template for AI services and tech products. Animations, gradients and dynamic blocks." },
      "Craftfolio": { title: "Craftfolio", description: "Modern portfolio template for designers, photographers and artists. Large project galleries and clean interface." },
      "Pulse Agency": { title: "Pulse Agency", description: "Energetic landing for marketing agencies. Contrasting colors, case studies and service blocks." },
      "Elevate": { title: "Elevate", description: "Universal business template for companies and consulting. Structured presentation builds brand trust." },
      "Flow SaaS": { title: "Flow SaaS", description: "Clean tech landing for SaaS products. Interface demo, advantages and pricing." },
      "Canvas": { title: "Canvas", description: "Gallery template for artists and art projects. Fullscreen images and smooth navigation create an exhibition feel." },
      "Momentum": { title: "Momentum", description: "Landing for startups and innovative products. Dynamic structure helps explain the idea and attract investors." },
      "Atlas": { title: "Atlas", description: "Corporate template for large companies. Clear page architecture and strict style create reliability." },
      "Spotlight": { title: "Spotlight", description: "The perfect personal brand template. For experts, coaches and consultants." },
      "Eventra": { title: "Eventra", description: "Landing for conferences, festivals and events. Schedule, speakers, registration and ticket sales." },
      "AppWave": { title: "AppWave", description: "Template for mobile app presentation. Interface visualization and benefits block." },
      "Marketly": { title: "Marketly", description: "Modern template for marketplaces and online platforms. Catalogs, product cards and filters." },
      "EduSpark": { title: "EduSpark", description: "Template for online schools and educational projects. Courses, instructors and student reviews." },
      "Urban Arch": { title: "Urban Arch", description: "Stylish template for architects and interior studios. Large project photos and strict geometry." },
      "FitMotion": { title: "FitMotion", description: "Dynamic template for fitness brands and trainers. Contrasting colors and energetic typography." },
      "TasteCraft": { title: "TasteCraft", description: "Elegant template for restaurants and cafes. Appetizing photos, menu and reservation system." },
      "NeoBlog": { title: "NeoBlog", description: "Modern editorial template for blogs and media. Focus on readability and visual content." },
      "Freelance Hub": { title: "Freelance Hub", description: "Practical template for freelancers. Portfolio, service list and project order form." },
      "Quantum": { title: "Quantum", description: "Futuristic template for AI startups and deep-tech projects. Glowing gradients and tech design." },
      "Infinity Grid": { title: "Infinity Grid", description: "Experimental template for creative brands. Non-standard grid and interactive navigation." },
      "LuxeAura": { title: "LuxeAura", description: "A minimal luxury brand website template with elegant typography and dark cinematic aesthetic." },
    } as Record<string, { title: string; description: string }>,
    demos: {
      minimalPortfolio: { back: "← Back", brand: "STUDIO", contact: "Contact", heroTitle: "Design with Purpose", heroSubtitle: "Minimal. Intentional. Beautiful.", projects: [{ title: "Brand Identity", type: "Branding" }, { title: "Web Design", type: "Digital" }, { title: "Photography", type: "Art Direction" }] as any[], testimonialsTitle: "Testimonials", testimonials: [{ text: "Exceptional attention to detail.", name: "Sarah K.", role: "CEO, TechCo" }, { text: "Transformed our brand completely.", name: "Mark L.", role: "Founder, StudioX" }] as any[], footer: "© 2026 Studio. All rights reserved." },
      darkStudio: { back: "← Back", brand: "VOID", connect: "Connect", heroTitle1: "Digital", heroTitle2: "Canvas", heroSubtitle: "We create immersive digital experiences that push boundaries.", showreel: "Watch Showreel", portfolioTitle: "Selected Work", works: [{ title: "Neon Genesis", category: "3D Art" }, { title: "Digital Void", category: "Motion" }, { title: "Cyber Bloom", category: "Interactive" }, { title: "Dark Matter", category: "Generative" }] as any[], servicesTitle: "Services", services: [{ title: "Brand Identity", desc: "Visual systems that resonate" }, { title: "Motion Design", desc: "Animation and kinetic typography" }, { title: "Digital Art", desc: "Generative and interactive pieces" }] as any[], footer: "© 2026 VOID Studio. All rights reserved." },
      saasStartup: { back: "← Back", brand: "LaunchPad", logIn: "Log in", startFree: "Start Free →", badge: "🚀 AI-Powered Platform", heroTitle1: "Scale Your Business", heroTitle2: "With Intelligence", heroSubtitle: "The modern platform that helps startups grow faster with AI-driven insights.", getStarted: "Get Started Free", watchDemo: "Watch Demo", featuresTitle: "Why Choose Us", features: [{ title: "AI Analytics", desc: "Smart insights powered by machine learning" }, { title: "Auto Scaling", desc: "Infrastructure that grows with you" }, { title: "Security First", desc: "SOC2 compliant, end-to-end encryption" }, { title: "Team Tools", desc: "Collaboration built for remote teams" }, { title: "API Access", desc: "RESTful API with full documentation" }, { title: "24/7 Support", desc: "Dedicated support team always available" }] as any[], pricingTitle: "Simple Pricing", plans: [{ name: "Starter", price: "$29/mo", desc: "For small teams getting started" }, { name: "Pro", price: "$99/mo", desc: "For growing businesses" }, { name: "Enterprise", price: "Custom", desc: "For large organizations" }] as any[], footer: "© 2026 LaunchPad. All rights reserved." },
      creativeAgency: { back: "← Back", brand: "BOLD", hireus: "Hire Us", heroTitle1: "We Create", heroTitle2: "Impact", heroSubtitle: "Bold ideas. Measurable results. We help brands stand out.", casesTitle: "Case Studies", cases: [{ title: "Nike Rebrand", client: "Nike Inc." }, { title: "Spotify Campaign", client: "Spotify AB" }, { title: "Tesla Launch", client: "Tesla Motors" }, { title: "Apple Retail", client: "Apple Inc." }] as any[], footer: "© 2026 BOLD Agency. All rights reserved." },
      personalBrand: { back: "← Back", brand: "Creator Kit", bookCall: "Book a Call", badge: "Your Personal Brand Partner", heroTitle: "Helping You Build & Grow Your Online Presence.", heroSubtitle: "I help creators, coaches, and entrepreneurs build authentic personal brands that attract opportunities.", cta: "Let's Work Together", servicesTitle: "Services & Packages", services: [{ title: "Brand Strategy", desc: "Define your unique positioning", price: "From $2,500" }, { title: "Content Creation", desc: "Professional photo, video & copy", price: "From $1,800" }, { title: "Social Media", desc: "Full-service content & engagement", price: "From $3,000/mo" }] as any[], successStories: "Success Stories", testimonials: [{ name: "Sarah K.", role: "Fitness Coach", text: "My followers grew 300% in 3 months!" }, { name: "Alex M.", role: "Tech Influencer", text: "Brand strategy session was worth every penny." }, { name: "Jordan L.", role: "Chef & Author", text: "My online presence finally matches my reputation." }] as any[], footer: "© 2026 Creator Kit. All rights reserved." },
      productShowcase: { back: "← Back", brand: "SoundPro", buyNow: "Buy Now", badge: "Next Generation Audio", heroTitle1: "Experience", heroTitle2: "Pure Sound", heroSubtitle: "Revolutionary noise-cancelling technology with studio-grade audio.", specsTitle: "Specifications", specs: [{ val: "40h", label: "Battery Life" }, { val: "45dB", label: "Noise Cancel" }, { val: "20Hz", label: "Frequency" }, { val: "320g", label: "Weight" }] as any[], reviewsTitle: "Reviews", reviews: [{ text: "Best headphones I've ever owned.", name: "Tech Review" }, { text: "Sound quality is unmatched.", name: "Audio Magazine" }] as any[], footer: "© 2026 SoundPro. All rights reserved." },
      startupPitch: { back: "← Back", brand: "GreenVolt", invest: "Invest Now", heroTitle: "The Future of Green Energy", heroSubtitle: "Join us in building a sustainable tomorrow. Series A — $10M round open.", sections: [{ label: "Problem", title: "Energy Crisis", desc: "Traditional energy sources are unsustainable and expensive." }, { label: "Solution", title: "Smart Solar Grid", desc: "AI-optimized solar microgrids that reduce costs by 60%." }, { label: "Market", title: "$500B Opportunity", desc: "The renewable energy market is growing 20% annually." }] as any[], teamTitle: "Our Team", team: [{ name: "Alex Chen", role: "CEO" }, { name: "Maria Lopez", role: "CTO" }, { name: "David Kim", role: "COO" }] as any[], footer: "© 2026 GreenVolt. All rights reserved." },
      digitalArtGallery: { back: "← Back", brand: "Siberiana", gallery: "Gallery", badge: "Digital Art Exhibition", heroTitle1: "Beyond", heroTitle2: "Reality", heroSubtitle: "Immersive digital art from visionary contemporary artists", worksTitle: "Current Exhibition", artworks: [{ title: "Eternal Whispers", artist: "Elena Vasquez" }, { title: "Cerulean Dreams", artist: "Marco Bellini" }, { title: "Golden Horizon", artist: "Yuki Tanaka" }, { title: "Midnight Reverie", artist: "Sofia Laurent" }, { title: "Velvet Echoes", artist: "Dmitri Volkov" }, { title: "Silent Passage", artist: "Amara Osei" }] as any[], footerName: "Siberiana Gallery", footerCities: "Moscow · London · Dubai" },
      corporateWebsite: { back: "← Back", brand: "Nextera", contact: "Contact Us", heroTitle1: "Building Trust.", heroTitle2: "Delivering Results.", heroSubtitle: "Enterprise solutions for a connected world.", learnMore: "Learn More", stats: [{ val: "500+", label: "Clients" }, { val: "15", label: "Years" }, { val: "99%", label: "Satisfaction" }, { val: "24/7", label: "Support" }] as any[], servicesTitle: "Our Services", services: [{ title: "Consulting", desc: "Strategic business advisory" }, { title: "Development", desc: "Custom software solutions" }, { title: "Analytics", desc: "Data-driven decision making" }] as any[], footer: "© 2026 Nextera Corp. All rights reserved." },
      startupAnimation: { back: "← Back", brand: "Kinetic", earlyAccess: "Early Access", heroTitle1: "Motion", heroTitle2: "Forward", heroSubtitle: "Where technology meets kinetic design. Building the future of interaction.", cta: "Join Waitlist", features: [{ title: "Kinetic Type", desc: "Dynamic typography that responds to user input" }, { title: "Micro-Interactions", desc: "Delightful details that enhance UX" }, { title: "3D Elements", desc: "Immersive spatial design components" }] as any[], footer: "© 2026 Kinetic Labs. All rights reserved." },
      marketplacePlatform: { back: "← Back", brand: "Bazaar", sell: "Start Selling", heroTitle1: "Discover &", heroTitle2: "Create", heroSubtitle: "The marketplace for digital creators and makers.", popularTitle: "Popular Items", items: [{ name: "UI Kit Pro", seller: "DesignCo", price: "$49" }, { name: "Icon Pack", seller: "PixelArt", price: "$29" }, { name: "Template Set", seller: "WebFlow", price: "$79" }, { name: "Font Bundle", seller: "TypeLab", price: "$39" }] as any[], sellersTitle: "Top Sellers", sellers: [{ name: "DesignCo", items: "142 items" }, { name: "PixelArt", items: "89 items" }, { name: "WebFlow", items: "67 items" }] as any[], footer: "© 2026 Bazaar. All rights reserved." },
      mobileAppLanding: { back: "← Back", brand: "Pulse", download: "Download", badge: "📱 #1 Productivity App", heroTitle1: "Your Life,", heroTitle2: "Simplified", heroSubtitle: "The smartest way to manage your day. Now on iOS & Android.", features: [{ icon: "⚡", title: "Lightning Fast", desc: "Instant sync across all devices" }, { icon: "🔒", title: "Secure", desc: "End-to-end encryption" }, { icon: "🎨", title: "Beautiful", desc: "Intuitive, delightful interface" }] as any[], footer: "© 2026 Pulse App. All rights reserved." },
      startupCommunity: { back: "← Back", brand: "Collective", join: "Join Free", badge: "🤝 5,000+ Members", heroTitle1: "Connect &", heroTitle2: "Grow Together", heroSubtitle: "The community for builders, creators, and innovators.", eventsTitle: "Upcoming Events", events: [{ date: "Mar 15", title: "Startup Meetup", type: "Networking" }, { date: "Mar 22", title: "Design Workshop", type: "Workshop" }, { date: "Apr 5", title: "Hackathon", type: "Competition" }] as any[], partnersTitle: "Partners", partners: ["Google", "Meta", "Stripe", "Vercel", "Figma"] as any[], footer: "© 2026 Collective. All rights reserved." },
      luxuryBrand: { back: "← Back", brand: "MAISON", collection: "Collection", heroTitle: "MAISON", heroSubtitle: "Timeless Elegance · Since 1924", pieces: [{ title: "The Midnight Collection", subtitle: "Autumn/Winter 2026" }, { title: "Silk & Shadow", subtitle: "Limited Edition" }] as any[], footerText: "Paris · Milan · Tokyo" },
      eventLanding: { back: "← Back", brand: "SUMMIT", tickets: "Get Tickets", date: "June 20-22 · 2026", heroTitle1: "SUMMIT", heroTitle2: "2026", heroSubtitle: "The Future of Innovation · 3 Days · 100+ Speakers", getTickets: "Get Tickets", speakersTitle: "Featured Speakers", speakers: [{ name: "Dr. Ada Chen", topic: "AI Ethics" }, { name: "James Rivera", topic: "Web3" }, { name: "Yuki Sato", topic: "Design" }, { name: "Maria Volkov", topic: "Startups" }] as any[], scheduleTitle: "Schedule", schedule: [{ time: "09:00", title: "Opening Keynote", speaker: "Dr. Ada Chen" }, { time: "11:00", title: "Panel: Future Tech", speaker: "Multiple speakers" }, { time: "14:00", title: "Workshop: AI Tools", speaker: "James Rivera" }] as any[], footer: "© 2026 Summit Conference. All rights reserved." },
      educationPlatform: { back: "← Back", signUp: "Sign Up Free", badge: "🎓 10,000+ Students Enrolled", heroTitle1: "Learn Without", heroTitle2: "Limits", heroSubtitle: "Master new skills with world-class instructors and interactive courses.", startLearning: "Start Learning", courses: [{ title: "Web Dev", count: "42 courses", color: "hsl(260,70%,55%)" }, { title: "Design", count: "38 courses", color: "hsl(340,75%,55%)" }, { title: "Data Science", count: "29 courses", color: "hsl(170,60%,45%)" }] as any[], instructorsTitle: "Top Instructors", instructors: [{ name: "Dr. Smith", subject: "Computer Science" }, { name: "Anna Lee", subject: "UX Design" }, { name: "Mark Chen", subject: "Data Science" }] as any[], footer: "© 2026 EduFlow. All rights reserved." },
      creativeBlog: { back: "← Back", brand: "The Journal", subscribe: "Subscribe", featuredLabel: "Featured", featuredTitle: "The Art of Digital Storytelling in Modern Design", featuredExcerpt: "Exploring how visual narratives shape our understanding of brand identity and user experience in the digital age.", readMore: "Read More", latestTitle: "Latest Posts", posts: [{ title: "Design Systems at Scale", category: "Design", date: "Mar 5, 2026" }, { title: "The Rise of AI in UX", category: "Technology", date: "Mar 2, 2026" }, { title: "Color Theory Reimagined", category: "Creative", date: "Feb 28, 2026" }] as any[], footer: "© 2026 The Journal. All rights reserved." },
      freelancerLanding: { back: "← Back", brand: "Jake.dev", hireMe: "Hire Me", heroTitle1: "Design That", heroTitle2: "Delivers", heroSubtitle: "Full-stack designer & developer. 7+ years of experience.", servicesTitle: "Services", services: [{ title: "Web Design", desc: "Modern responsive websites", price: "From $3,000" }, { title: "Branding", desc: "Complete brand identity", price: "From $2,000" }, { title: "Development", desc: "React, Node.js, TypeScript", price: "From $4,000" }] as any[], portfolio: [{}, {}, {}, {}] as any[], pricingTitle: "Packages", pricing: [{ name: "Basic", price: "$3K", desc: "Single page site" }, { name: "Pro", price: "$7K", desc: "Full website + branding" }, { name: "Premium", price: "$15K", desc: "Complete digital presence" }] as any[], footer: "© 2026 Jake.dev. All rights reserved." },
      startupDashboard: { back: "← Back", brand: "DataFlow", startFree: "Start Free", badge: "📊 Analytics Dashboard", heroTitle1: "Your Data,", heroTitle2: "Your Way", heroSubtitle: "The most intuitive analytics platform for modern SaaS companies.", metrics: [{ label: "Revenue", val: "$128.4K", color: "hsl(130,60%,50%)" }, { label: "Users", val: "24,891", color: "hsl(200,80%,60%)" }, { label: "Conversion", val: "4.2%", color: "hsl(40,90%,55%)" }, { label: "Growth", val: "+32%", color: "hsl(0,85%,55%)" }] as any[], features: [{ title: "Real-time Data", desc: "Live dashboards updated every second" }, { title: "Custom Reports", desc: "Build reports that matter to your business" }, { title: "Team Sharing", desc: "Collaborate with your entire organization" }] as any[], footer: "© 2026 DataFlow. All rights reserved." },
      architectureStudio: { back: "← Back", contact: "Contact", badge: "Architecture · Design · Build", heroTitle1: "Form", heroTitle2: "Follows", heroTitle3: "Function", heroSubtitle: "Award-winning architectural solutions that blend aesthetics with purpose.", showcase: "Project Showcase", projectsTitle: "Selected Projects", projects: [{ title: "Glass Pavilion", type: "Residential" }, { title: "Urban Core Tower", type: "Commercial" }, { title: "Zen Garden House", type: "Residential" }] as any[], footer: "© 2026 Forma Studio. All rights reserved." },
      fitnessBrand: { back: "← Back", brand: "APEX", joinNow: "Join Now", badge: "Push · Grind · Conquer", heroTitle1: "NO", heroTitle2: "LIMITS.", heroTitle3: "NO EXCUSES.", heroSubtitle: "Transform your body with AI-powered training programs.", startNow: "Start Training", stats: [{ label: "Workouts", val: "200+" }, { label: "Trainers", val: "50+" }, { label: "Members", val: "10K+" }] as any[], programsTitle: "Programs", programs: [{ title: "Strength", desc: "Build muscle and power" }, { title: "HIIT", desc: "High-intensity fat burning" }, { title: "Yoga", desc: "Flexibility and mindfulness" }] as any[], footer: "© 2026 APEX Fitness. All rights reserved." },
      restaurantWebsite: { back: "← Back", brand: "La Maison", reserve: "Reserve a Table", badge: "Est. 2018 · Fine Dining", heroTitle: "La Maison", heroSubtitle: "Where culinary art meets timeless elegance", menuTitle: "Our Menu", dishes: [{ name: "Truffle Risotto", desc: "Arborio rice, black truffle, parmesan", price: "$48" }, { name: "Wagyu Steak", desc: "A5 grade, seasonal vegetables", price: "$89" }, { name: "Lobster Bisque", desc: "Atlantic lobster, cream, cognac", price: "$32" }, { name: "Crème Brûlée", desc: "Madagascar vanilla, caramelized sugar", price: "$18" }] as any[], footerAddr: "42 Rue de Rivoli, Paris" },
      aiProductLanding: { back: "← Back", brand: "NeuralOS", tryFree: "Try Free", heroTitle1: "Intelligence", heroTitle2: "Amplified", heroSubtitle: "Next-gen AI that transforms how you work. Process, analyze, create — faster than ever.", getStarted: "Get Started", watchDemo: "Watch Demo", features: [{ title: "Natural Language", desc: "Understand and generate human-like text" }, { title: "Vision AI", desc: "Process images and video in real-time" }, { title: "Auto Learning", desc: "Models that improve with every interaction" }] as any[], footer: "© 2026 NeuralOS. All rights reserved." },
      creativeStartup: { back: "← Back", brand: "FORMA", explore: "Explore", heroTitle1: "Break The", heroTitle2: "Rules", heroTitle3: "Build New", heroSubtitle: "We design experiences that defy convention. Organic. Dynamic. Unforgettable.", cta: "Start a Project", highlights: [{ title: "Organic Design", desc: "Flowing shapes that breathe" }, { title: "Bold Colors", desc: "Palettes that command attention" }, { title: "Motion First", desc: "Every element tells a story" }] as any[], values: [{ icon: "🎨", title: "Creative" }, { icon: "⚡", title: "Fast" }, { icon: "🌱", title: "Organic" }, { icon: "🔥", title: "Bold" }] as any[], footer: "© 2026 FORMA. All rights reserved." },
      luxeAuraBrand: { back: "← Back", brand: "LuxeAura", explore: "Explore", badge: "Premium Brand Template", heroTitle: "LuxeAura", heroSubtitle: "A minimal luxury brand website template with elegant typography and dark cinematic aesthetic.", cta: "Discover Collection", featuresTitle: "Features", featuresSubtitle: "Clean layout, bold typography and responsive design.", features: [{ title: "Modern Design", desc: "Clean layout, bold typography and responsive grid.", image: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&h=400&fit=crop" }, { title: "Responsive", desc: "Optimized for mobile, tablet and desktop screens.", image: "https://images.unsplash.com/photo-1551434678-e076c223a692?w=600&h=400&fit=crop" }, { title: "Easy to Customize", desc: "Simple structure that makes editing fast and easy.", image: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=600&h=400&fit=crop" }] as any[], aboutTitle: "About this template", aboutText: "This template is designed as a modern landing page structure suitable for startups, creative studios and online products. It includes hero sections, feature blocks and call-to-action areas.", footer: "Template Demo • Built for FormCraft Templates" },
    },
  },
  ru: {
    nav: { templates: "Шаблоны", showcase: "Витрина", about: "О проекте", getStarted: "Начать", searchPlaceholder: "Поиск шаблонов..." },
    hero: { badge: "Премиум шаблоны", line1: "Создаём", line2: "цифровое", line3: "совершенство.", subtitle: "Высококонверсионные шаблоны лендингов, созданные с точностью. Разработаны для продвижения вашего бренда.", explore: "Смотреть шаблоны", viewShowcase: "Витрина работ", templateCount: "24 шаблона", responsive: "Адаптивный дизайн", updates: "Бесплатные обновления" },
    featured: { label: "Избранное", title: "Лучшие работы" },
    collection: { label: "Коллекция", title: "Все шаблоны", all: "Все", noResults: "Шаблоны не найдены", noResultsHint: "Попробуйте выбрать другую категорию.", clearFilters: "Сбросить фильтры", preview: "Просмотр" },
    detail: {
      back: "Назад к шаблонам", getTemplate: "Получить шаблон", orderPrefix: "Я хотел бы заказать сайт по шаблону", livePreview: "Живой просмотр", included: "Что включено", creators: "200+ авторов", creatorsDesc: "уже используют этот шаблон", notFound: "Шаблон не найден", notFoundDesc: "Шаблон, который вы ищете, не существует или был удалён.", returnHome: "На главную",
      features: { responsive: "Полная адаптивность", responsiveDesc: "Идеальное отображение на любом устройстве.", performance: "Высокая скорость", performanceDesc: "Оптимизирован для скорости, SEO и конверсий.", code: "Чистый код", codeDesc: "Хорошо структурированный, понятный и легко расширяемый.", design: "Уникальный дизайн", designDesc: "Авторский дизайн с вниманием к деталям.", browser: "Кросс-браузерность", browserDesc: "Протестирован во всех современных браузерах.", practices: "Лучшие практики", practicesDesc: "Создан с учётом доступности и безопасности." },
    },
    footer: {
      title: "Готовы к запуску?", subtitle: "Опишите проект — я предложу структуру, формат и сроки. Ответ в течение 24 часов.",
      form: { name: "Имя", namePlaceholder: "Ваше имя", contact: "Контакт (Telegram или Email)", contactPlaceholder: "@telegram или email", projectType: "Тип проекта", projectTypes: ["Лендинг", "Редизайн", "Другое"] as readonly string[], timeline: "Сроки", timelines: ["Стандарт", "Быстро 3–5 дней"] as readonly string[], description: "Краткое описание", descriptionPlaceholder: "Расскажите о вашем проекте...", submit: "Начать проект" },
      contacts: { telegram: "Telegram", telegramDesc: "Самый быстрый ответ", email: "Email", emailDesc: "Для официальных запросов" },
      remote: "Удалённо по всему миру · RU / EN", rights: "FormCraft. Все права защищены.",
    },
    about: { title: "О проекте", content: ["Я создаю лендинги как стратегический инструмент влияния.", "Каждый проект начинается не с дизайна —\nа с анализа продукта, аудитории и точки роста.", "Сначала — логика.\nЗатем — структура.\nПотом — визуал.\nИ только после — эффект.", "Я работаю в разных стилях —\nот сдержанной luxury-эстетики до смелого digital —\nно неизменно одно:", "Чёткость.\nКонтроль внимания.\nКонверсия.", "Лендинг — это не просто красивая страница.\nЭто управляемый сценарий взаимодействия.", "И каждый пиксель в нём имеет цель."] },
    marquee: ["Лендинги", "Интернет-магазины", "SaaS", "Портфолио", "Креатив", "Люкс", "Интерактив", "Минимализм"] as readonly string[],
    categories: { "All": "Все", "E-commerce": "Интернет-магазин", "Creative": "Креатив", "Luxury": "Люкс", "Personal": "Персональный", "Product": "Продукт", "SaaS": "SaaS", "Lifestyle": "Лайфстайл", "Food & Drink": "Еда и напитки", "Entertainment": "Развлечения", "Business": "Бизнес", "Fintech": "Финтех", "Media": "Медиа" } as Record<string, string>,
    styles: { minimal: "Минимал", brutalist: "Бруталист", luxury: "Люкс", futuristic: "Футуризм" } as Record<string, string>,
    niches: { SaaS: "SaaS", portfolio: "Портфолио", marketplace: "Маркетплейс", event: "Событие" } as Record<string, string>,
    moods: { clean: "Чистый", bold: "Смелый", cinematic: "Кинематографичный", playful: "Игривый" } as Record<string, string>,
    templateData: {
      "Nova Studio": { title: "Nova Studio", description: "Минималистичный шаблон для креативных студий и дизайнеров. Чистая типографика, большие изображения и современная сетка." },
      "DarkMatter": { title: "DarkMatter", description: "Тёмный кинематографичный лендинг для digital-агентств и арт-проектов. Неоновые акценты и плавные анимации." },
      "Launchpad": { title: "Launchpad", description: "Идеальный шаблон для стартапов. Чёткая структура помогает быстро донести ценность продукта и конвертировать посетителей." },
      "Velour": { title: "Velour", description: "Элегантный премиальный шаблон для luxury-брендов и дизайнерских продуктов. Мягкая цветовая палитра и утончённая типографика." },
      "Orbit": { title: "Orbit", description: "Футуристичный шаблон для AI-сервисов и технологических продуктов. Анимации, градиенты и динамичные блоки." },
      "Craftfolio": { title: "Craftfolio", description: "Современный шаблон портфолио для дизайнеров, фотографов и художников. Большие галереи проектов и чистый интерфейс." },
      "Pulse Agency": { title: "Pulse Agency", description: "Энергичный лендинг для маркетинговых агентств. Контрастные цвета, кейсы и блоки услуг." },
      "Elevate": { title: "Elevate", description: "Универсальный бизнес-шаблон для компаний и консалтинга. Структурированная подача информации выстраивает доверие к бренду." },
      "Flow SaaS": { title: "Flow SaaS", description: "Чистый технологичный лендинг для SaaS-продуктов. Демонстрация интерфейса, преимущества и тарифы." },
      "Canvas": { title: "Canvas", description: "Галерейный шаблон для художников и арт-проектов. Полноэкранные изображения и плавная навигация создают эффект выставки." },
      "Momentum": { title: "Momentum", description: "Лендинг для стартапов и инновационных продуктов. Динамичная структура помогает объяснить идею и привлечь инвесторов." },
      "Atlas": { title: "Atlas", description: "Корпоративный шаблон для крупных компаний. Чёткая архитектура страниц и строгий стиль создают ощущение надёжности." },
      "Spotlight": { title: "Spotlight", description: "Идеальный шаблон для персонального бренда. Для экспертов, коучей и консультантов." },
      "Eventra": { title: "Eventra", description: "Лендинг для конференций, фестивалей и мероприятий. Расписание, спикеры, регистрация и продажа билетов." },
      "AppWave": { title: "AppWave", description: "Шаблон для презентации мобильных приложений. Визуализация интерфейса и блок преимуществ." },
      "Marketly": { title: "Marketly", description: "Современный шаблон для маркетплейсов и онлайн-площадок. Каталоги, карточки продуктов и фильтры." },
      "EduSpark": { title: "EduSpark", description: "Шаблон для онлайн-школ и образовательных проектов. Курсы, преподаватели и отзывы студентов." },
      "Urban Arch": { title: "Urban Arch", description: "Стильный шаблон для архитекторов и интерьерных студий. Большие фотографии проектов и строгая геометрия." },
      "FitMotion": { title: "FitMotion", description: "Динамичный шаблон для фитнес-брендов и тренеров. Контрастные цвета и энергичная типографика." },
      "TasteCraft": { title: "TasteCraft", description: "Элегантный шаблон для ресторанов и кафе. Аппетитные фотографии, меню и система бронирования." },
      "NeoBlog": { title: "NeoBlog", description: "Современный редакционный шаблон для блогов и медиа. Фокус на читаемости и визуальной подаче контента." },
      "Freelance Hub": { title: "Freelance Hub", description: "Практичный шаблон для фрилансеров. Портфолио, список услуг и форма заказа проекта." },
      "Quantum": { title: "Quantum", description: "Футуристичный шаблон для AI-стартапов и deep-tech проектов. Светящиеся градиенты и технологичный дизайн." },
      "Infinity Grid": { title: "Infinity Grid", description: "Экспериментальный шаблон для креативных брендов. Нестандартная сетка и интерактивная навигация." },
      "LuxeAura": { title: "LuxeAura", description: "Минималистичный шаблон для премиум-брендов с элегантной типографикой и тёмной кинематографичной эстетикой." },
    } as Record<string, { title: string; description: string }>,
    demos: {
      minimalPortfolio: { back: "← Назад", brand: "STUDIO", contact: "Контакты", heroTitle: "Дизайн с целью", heroSubtitle: "Минимализм. Осознанность. Красота.", projects: [{ title: "Айдентика бренда", type: "Брендинг" }, { title: "Веб-дизайн", type: "Диджитал" }, { title: "Фотография", type: "Арт-дирекшн" }] as any[], testimonialsTitle: "Отзывы", testimonials: [{ text: "Исключительное внимание к деталям.", name: "Сара К.", role: "CEO, TechCo" }, { text: "Полностью преобразили наш бренд.", name: "Марк Л.", role: "Основатель, StudioX" }] as any[], footer: "© 2026 Studio. Все права защищены." },
      darkStudio: { back: "← Назад", brand: "VOID", connect: "Связаться", heroTitle1: "Цифровое", heroTitle2: "полотно", heroSubtitle: "Мы создаём иммерсивные цифровые опыты, раздвигающие границы.", showreel: "Смотреть шоурил", portfolioTitle: "Избранные работы", works: [{ title: "Neon Genesis", category: "3D Арт" }, { title: "Digital Void", category: "Моушн" }, { title: "Cyber Bloom", category: "Интерактив" }, { title: "Dark Matter", category: "Генеративное" }] as any[], servicesTitle: "Услуги", services: [{ title: "Айдентика", desc: "Визуальные системы, которые резонируют" }, { title: "Моушн-дизайн", desc: "Анимация и кинетическая типографика" }, { title: "Цифровое искусство", desc: "Генеративные и интерактивные работы" }] as any[], footer: "© 2026 VOID Studio. Все права защищены." },
      saasStartup: { back: "← Назад", brand: "LaunchPad", logIn: "Войти", startFree: "Начать бесплатно →", badge: "🚀 ИИ-платформа", heroTitle1: "Масштабируйте бизнес", heroTitle2: "с умом", heroSubtitle: "Современная платформа, которая помогает стартапам расти быстрее.", getStarted: "Начать бесплатно", watchDemo: "Смотреть демо", featuresTitle: "Почему мы", features: [{ title: "ИИ-аналитика", desc: "Умные инсайты на основе машинного обучения" }, { title: "Автомасштабирование", desc: "Инфраструктура, растущая вместе с вами" }, { title: "Безопасность", desc: "SOC2, сквозное шифрование" }, { title: "Командная работа", desc: "Инструменты для удалённых команд" }, { title: "API доступ", desc: "RESTful API с полной документацией" }, { title: "Поддержка 24/7", desc: "Выделенная команда поддержки" }] as any[], pricingTitle: "Тарифы", plans: [{ name: "Старт", price: "$29/мес", desc: "Для небольших команд" }, { name: "Про", price: "$99/мес", desc: "Для растущего бизнеса" }, { name: "Корпорация", price: "По запросу", desc: "Для крупных организаций" }] as any[], footer: "© 2026 LaunchPad. Все права защищены." },
      creativeAgency: { back: "← Назад", brand: "BOLD", hireus: "Нанять нас", heroTitle1: "Мы создаём", heroTitle2: "влияние", heroSubtitle: "Смелые идеи. Измеримые результаты. Помогаем брендам выделяться.", casesTitle: "Кейсы", cases: [{ title: "Ребрендинг Nike", client: "Nike Inc." }, { title: "Кампания Spotify", client: "Spotify AB" }, { title: "Запуск Tesla", client: "Tesla Motors" }, { title: "Apple Retail", client: "Apple Inc." }] as any[], footer: "© 2026 BOLD Agency. Все права защищены." },
      personalBrand: { back: "← Назад", brand: "Creator Kit", bookCall: "Записаться на звонок", badge: "Ваш партнёр по личному бренду", heroTitle: "Помогаю строить и развивать ваше онлайн-присутствие.", heroSubtitle: "Помогаю авторам, коучам и предпринимателям строить аутентичные личные бренды.", cta: "Давайте работать вместе", servicesTitle: "Услуги и пакеты", services: [{ title: "Стратегия бренда", desc: "Определите уникальное позиционирование", price: "От $2,500" }, { title: "Создание контента", desc: "Фото, видео и копирайтинг", price: "От $1,800" }, { title: "Соцсети", desc: "Контент-план и вовлечение", price: "От $3,000/мес" }] as any[], successStories: "Истории успеха", testimonials: [{ name: "Сара К.", role: "Фитнес-тренер", text: "Мои подписчики выросли на 300% за 3 месяца!" }, { name: "Алекс М.", role: "Tech-блогер", text: "Стратегия бренда стоила каждого рубля." }, { name: "Джордан Л.", role: "Шеф-повар", text: "Онлайн-присутствие наконец соответствует репутации." }] as any[], footer: "© 2026 Creator Kit. Все права защищены." },
      productShowcase: { back: "← Назад", brand: "SoundPro", buyNow: "Купить", badge: "Аудио нового поколения", heroTitle1: "Испытайте", heroTitle2: "чистый звук", heroSubtitle: "Революционное шумоподавление и студийное качество звука.", specsTitle: "Характеристики", specs: [{ val: "40ч", label: "Батарея" }, { val: "45дБ", label: "Шумоподавление" }, { val: "20Гц", label: "Частота" }, { val: "320г", label: "Вес" }] as any[], reviewsTitle: "Отзывы", reviews: [{ text: "Лучшие наушники, что у меня были.", name: "Tech Review" }, { text: "Качество звука непревзойдённое.", name: "Audio Magazine" }] as any[], footer: "© 2026 SoundPro. Все права защищены." },
      startupPitch: { back: "← Назад", brand: "GreenVolt", invest: "Инвестировать", heroTitle: "Будущее зелёной энергии", heroSubtitle: "Присоединяйтесь к строительству устойчивого будущего. Раунд A — $10M.", sections: [{ label: "Проблема", title: "Энергетический кризис", desc: "Традиционные источники энергии неустойчивы и дороги." }, { label: "Решение", title: "Умная солнечная сеть", desc: "ИИ-оптимизированные солнечные микросети, снижающие расходы на 60%." }, { label: "Рынок", title: "Возможность на $500B", desc: "Рынок возобновляемой энергии растёт на 20% ежегодно." }] as any[], teamTitle: "Команда", team: [{ name: "Алекс Чен", role: "CEO" }, { name: "Мария Лопес", role: "CTO" }, { name: "Дэвид Ким", role: "COO" }] as any[], footer: "© 2026 GreenVolt. Все права защищены." },
      digitalArtGallery: { back: "← Назад", brand: "Siberiana", gallery: "Галерея", badge: "Выставка цифрового искусства", heroTitle1: "За гранью", heroTitle2: "реальности", heroSubtitle: "Иммерсивное цифровое искусство от визионерских современных художников", worksTitle: "Текущая выставка", artworks: [{ title: "Вечные шёпоты", artist: "Елена Васкес" }, { title: "Лазурные сны", artist: "Марко Беллини" }, { title: "Золотой горизонт", artist: "Юки Танака" }, { title: "Полуночная грёза", artist: "София Лоран" }, { title: "Бархатное эхо", artist: "Дмитрий Волков" }, { title: "Тихий путь", artist: "Амара Осей" }] as any[], footerName: "Siberiana Галерея", footerCities: "Москва · Лондон · Дубай" },
      corporateWebsite: { back: "← Назад", brand: "Nextera", contact: "Связаться", heroTitle1: "Строим доверие.", heroTitle2: "Даём результат.", heroSubtitle: "Корпоративные решения для связанного мира.", learnMore: "Подробнее", stats: [{ val: "500+", label: "Клиентов" }, { val: "15", label: "Лет" }, { val: "99%", label: "Довольных" }, { val: "24/7", label: "Поддержка" }] as any[], servicesTitle: "Услуги", services: [{ title: "Консалтинг", desc: "Стратегический бизнес-консалтинг" }, { title: "Разработка", desc: "Заказное ПО" }, { title: "Аналитика", desc: "Решения на основе данных" }] as any[], footer: "© 2026 Nextera Corp. Все права защищены." },
      startupAnimation: { back: "← Назад", brand: "Kinetic", earlyAccess: "Ранний доступ", heroTitle1: "Движение", heroTitle2: "вперёд", heroSubtitle: "Где технологии встречаются с кинетическим дизайном.", cta: "В лист ожидания", features: [{ title: "Кинетическая типографика", desc: "Динамический текст, реагирующий на пользователя" }, { title: "Микро-взаимодействия", desc: "Восхитительные детали, улучшающие UX" }, { title: "3D элементы", desc: "Иммерсивные пространственные компоненты" }] as any[], footer: "© 2026 Kinetic Labs. Все права защищены." },
      marketplacePlatform: { back: "← Назад", brand: "Bazaar", sell: "Начать продавать", heroTitle1: "Открывайте &", heroTitle2: "создавайте", heroSubtitle: "Маркетплейс для цифровых создателей.", popularTitle: "Популярное", items: [{ name: "UI Kit Pro", seller: "DesignCo", price: "$49" }, { name: "Набор иконок", seller: "PixelArt", price: "$29" }, { name: "Шаблоны", seller: "WebFlow", price: "$79" }, { name: "Шрифты", seller: "TypeLab", price: "$39" }] as any[], sellersTitle: "Топ продавцы", sellers: [{ name: "DesignCo", items: "142 товара" }, { name: "PixelArt", items: "89 товаров" }, { name: "WebFlow", items: "67 товаров" }] as any[], footer: "© 2026 Bazaar. Все права защищены." },
      mobileAppLanding: { back: "← Назад", brand: "Pulse", download: "Скачать", badge: "📱 Приложение #1", heroTitle1: "Ваша жизнь,", heroTitle2: "проще", heroSubtitle: "Умный способ управлять своим днём. Теперь на iOS и Android.", features: [{ icon: "⚡", title: "Молниеносно", desc: "Мгновенная синхронизация на всех устройствах" }, { icon: "🔒", title: "Безопасно", desc: "Сквозное шифрование" }, { icon: "🎨", title: "Красиво", desc: "Интуитивный, приятный интерфейс" }] as any[], footer: "© 2026 Pulse App. Все права защищены." },
      startupCommunity: { back: "← Назад", brand: "Collective", join: "Вступить бесплатно", badge: "🤝 5 000+ участников", heroTitle1: "Общайтесь &", heroTitle2: "растите вместе", heroSubtitle: "Сообщество для создателей и инноваторов.", eventsTitle: "Ближайшие события", events: [{ date: "15 мар", title: "Стартап-митап", type: "Нетворкинг" }, { date: "22 мар", title: "Дизайн-воркшоп", type: "Мастер-класс" }, { date: "5 апр", title: "Хакатон", type: "Соревнование" }] as any[], partnersTitle: "Партнёры", partners: ["Google", "Meta", "Stripe", "Vercel", "Figma"] as any[], footer: "© 2026 Collective. Все права защищены." },
      luxuryBrand: { back: "← Назад", brand: "MAISON", collection: "Коллекция", heroTitle: "MAISON", heroSubtitle: "Вечная элегантность · С 1924 года", pieces: [{ title: "Полуночная коллекция", subtitle: "Осень/Зима 2026" }, { title: "Шёлк и тень", subtitle: "Лимитированная серия" }] as any[], footerText: "Париж · Милан · Токио" },
      eventLanding: { back: "← Назад", brand: "SUMMIT", tickets: "Билеты", date: "20-22 июня · 2026", heroTitle1: "SUMMIT", heroTitle2: "2026", heroSubtitle: "Будущее инноваций · 3 дня · 100+ спикеров", getTickets: "Купить билеты", speakersTitle: "Спикеры", speakers: [{ name: "Д-р Ада Чен", topic: "Этика ИИ" }, { name: "Джеймс Ривера", topic: "Web3" }, { name: "Юки Сато", topic: "Дизайн" }, { name: "Мария Волкова", topic: "Стартапы" }] as any[], scheduleTitle: "Расписание", schedule: [{ time: "09:00", title: "Открытие", speaker: "Д-р Ада Чен" }, { time: "11:00", title: "Панель: Будущее технологий", speaker: "Несколько спикеров" }, { time: "14:00", title: "Воркшоп: ИИ-инструменты", speaker: "Джеймс Ривера" }] as any[], footer: "© 2026 Summit Conference. Все права защищены." },
      educationPlatform: { back: "← Назад", signUp: "Регистрация", badge: "🎓 10 000+ студентов", heroTitle1: "Учись без", heroTitle2: "границ", heroSubtitle: "Осваивайте навыки с лучшими преподавателями и интерактивными курсами.", startLearning: "Начать обучение", courses: [{ title: "Веб-разработка", count: "42 курса", color: "hsl(260,70%,55%)" }, { title: "Дизайн", count: "38 курсов", color: "hsl(340,75%,55%)" }, { title: "Data Science", count: "29 курсов", color: "hsl(170,60%,45%)" }] as any[], instructorsTitle: "Преподаватели", instructors: [{ name: "Д-р Смит", subject: "Информатика" }, { name: "Анна Ли", subject: "UX Дизайн" }, { name: "Марк Чен", subject: "Data Science" }] as any[], footer: "© 2026 EduFlow. Все права защищены." },
      creativeBlog: { back: "← Назад", brand: "The Journal", subscribe: "Подписаться", featuredLabel: "Избранное", featuredTitle: "Искусство цифрового сторителлинга в современном дизайне", featuredExcerpt: "Как визуальные нарративы формируют наше понимание бренда и пользовательского опыта в цифровую эпоху.", readMore: "Читать далее", latestTitle: "Последние статьи", posts: [{ title: "Дизайн-системы в масштабе", category: "Дизайн", date: "5 мар 2026" }, { title: "ИИ в UX-дизайне", category: "Технологии", date: "2 мар 2026" }, { title: "Теория цвета заново", category: "Креатив", date: "28 фев 2026" }] as any[], footer: "© 2026 The Journal. Все права защищены." },
      freelancerLanding: { back: "← Назад", brand: "Jake.dev", hireMe: "Нанять меня", heroTitle1: "Дизайн, который", heroTitle2: "работает", heroSubtitle: "Фулстек-дизайнер и разработчик. 7+ лет опыта.", servicesTitle: "Услуги", services: [{ title: "Веб-дизайн", desc: "Современные адаптивные сайты", price: "От $3,000" }, { title: "Брендинг", desc: "Полная айдентика бренда", price: "От $2,000" }, { title: "Разработка", desc: "React, Node.js, TypeScript", price: "От $4,000" }] as any[], portfolio: [{}, {}, {}, {}] as any[], pricingTitle: "Пакеты", pricing: [{ name: "Базовый", price: "$3K", desc: "Одностраничный сайт" }, { name: "Про", price: "$7K", desc: "Полный сайт + брендинг" }, { name: "Премиум", price: "$15K", desc: "Полное цифровое присутствие" }] as any[], footer: "© 2026 Jake.dev. Все права защищены." },
      startupDashboard: { back: "← Назад", brand: "DataFlow", startFree: "Начать бесплатно", badge: "📊 Панель аналитики", heroTitle1: "Ваши данные,", heroTitle2: "ваши правила", heroSubtitle: "Самая интуитивная аналитическая платформа для SaaS-компаний.", metrics: [{ label: "Доход", val: "$128.4K", color: "hsl(130,60%,50%)" }, { label: "Пользователи", val: "24 891", color: "hsl(200,80%,60%)" }, { label: "Конверсия", val: "4.2%", color: "hsl(40,90%,55%)" }, { label: "Рост", val: "+32%", color: "hsl(0,85%,55%)" }] as any[], features: [{ title: "Данные в реальном времени", desc: "Живые дашборды, обновляемые каждую секунду" }, { title: "Кастомные отчёты", desc: "Отчёты, важные для вашего бизнеса" }, { title: "Командный доступ", desc: "Совместная работа всей организации" }] as any[], footer: "© 2026 DataFlow. Все права защищены." },
      architectureStudio: { back: "← Назад", contact: "Контакты", badge: "Архитектура · Дизайн · Строительство", heroTitle1: "Форма", heroTitle2: "следует", heroTitle3: "функции", heroSubtitle: "Отмеченные наградами архитектурные решения.", showcase: "Витрина проектов", projectsTitle: "Избранные проекты", projects: [{ title: "Стеклянный павильон", type: "Жилое" }, { title: "Башня Urban Core", type: "Коммерческое" }, { title: "Дом с дзен-садом", type: "Жилое" }] as any[], footer: "© 2026 Forma Studio. Все права защищены." },
      fitnessBrand: { back: "← Назад", brand: "APEX", joinNow: "Вступить", badge: "Давить · Пахать · Побеждать", heroTitle1: "БЕЗ", heroTitle2: "ГРАНИЦ.", heroTitle3: "БЕЗ ОПРАВДАНИЙ.", heroSubtitle: "Трансформируйте тело с ИИ-программами тренировок.", startNow: "Начать", stats: [{ label: "Тренировки", val: "200+" }, { label: "Тренеры", val: "50+" }, { label: "Участники", val: "10K+" }] as any[], programsTitle: "Программы", programs: [{ title: "Сила", desc: "Набор мышц и мощи" }, { title: "HIIT", desc: "Интенсивное жиросжигание" }, { title: "Йога", desc: "Гибкость и осознанность" }] as any[], footer: "© 2026 APEX Fitness. Все права защищены." },
      restaurantWebsite: { back: "← Назад", brand: "La Maison", reserve: "Забронировать стол", badge: "С 2018 года · Высокая кухня", heroTitle: "La Maison", heroSubtitle: "Где кулинарное искусство встречается с вечной элегантностью", menuTitle: "Наше меню", dishes: [{ name: "Ризотто с трюфелем", desc: "Рис арборио, чёрный трюфель, пармезан", price: "$48" }, { name: "Стейк Вагю", desc: "Категория A5, сезонные овощи", price: "$89" }, { name: "Крем-суп из лобстера", desc: "Атлантический лобстер, сливки, коньяк", price: "$32" }, { name: "Крем-брюле", desc: "Мадагаскарская ваниль, карамелизированный сахар", price: "$18" }] as any[], footerAddr: "42 Rue de Rivoli, Париж" },
      aiProductLanding: { back: "← Назад", brand: "NeuralOS", tryFree: "Попробовать", heroTitle1: "Интеллект", heroTitle2: "усиленный", heroSubtitle: "ИИ нового поколения, трансформирующий вашу работу.", getStarted: "Начать", watchDemo: "Смотреть демо", features: [{ title: "Естественный язык", desc: "Понимание и генерация текста" }, { title: "Vision AI", desc: "Обработка изображений и видео" }, { title: "Авто-обучение", desc: "Модели, улучшающиеся с каждым использованием" }] as any[], footer: "© 2026 NeuralOS. Все права защищены." },
      creativeStartup: { back: "← Назад", brand: "FORMA", explore: "Исследовать", heroTitle1: "Ломай", heroTitle2: "правила", heroTitle3: "Создавай новое", heroSubtitle: "Мы проектируем опыт, бросающий вызов условностям.", cta: "Начать проект", highlights: [{ title: "Органичный дизайн", desc: "Формы, которые дышат" }, { title: "Смелые цвета", desc: "Палитры, привлекающие внимание" }, { title: "Движение прежде всего", desc: "Каждый элемент рассказывает историю" }] as any[], values: [{ icon: "🎨", title: "Креатив" }, { icon: "⚡", title: "Быстро" }, { icon: "🌱", title: "Органика" }, { icon: "🔥", title: "Смело" }] as any[], footer: "© 2026 FORMA. Все права защищены." },
      luxeAuraBrand: { back: "← Назад", brand: "LuxeAura", explore: "Обзор", badge: "Премиум шаблон бренда", heroTitle: "LuxeAura", heroSubtitle: "Минималистичный шаблон для премиум-бренда с элегантной типографикой и тёмной кинематографичной эстетикой.", cta: "Смотреть коллекцию", featuresTitle: "Возможности", featuresSubtitle: "Чистый макет, жирная типографика и адаптивный дизайн.", features: [{ title: "Современный дизайн", desc: "Чистый макет, жирная типографика и адаптивная сетка.", image: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&h=400&fit=crop" }, { title: "Адаптивность", desc: "Оптимизирован для мобильных, планшетов и ПК.", image: "https://images.unsplash.com/photo-1551434678-e076c223a692?w=600&h=400&fit=crop" }, { title: "Легко настроить", desc: "Простая структура для быстрого редактирования.", image: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=600&h=400&fit=crop" }] as any[], aboutTitle: "Об этом шаблоне", aboutText: "Шаблон разработан как современная структура лендинга для стартапов, креативных студий и онлайн-продуктов. Включает hero-секции, блоки фич и призывы к действию.", footer: "Демо шаблона • Создано для FormCraft Templates" },
    },
  },
} as const;

export type Translations = (typeof translations)["en"] | (typeof translations)["ru"];

interface LangContextType {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: Translations;
}

const LangContext = createContext<LangContextType | null>(null);

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    if (typeof window !== "undefined") {
      const saved = localStorage.getItem("anna-lang");
      if (saved === "ru" || saved === "en") return saved;
    }
    return "en";
  });

  const setLang = (newLang: Lang) => {
    setLangState(newLang);
    localStorage.setItem("anna-lang", newLang);
    document.documentElement.lang = newLang;
  };

  useEffect(() => {
    document.documentElement.lang = lang;
  }, [lang]);

  const t = translations[lang];

  return (
    <LangContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  const ctx = useContext(LangContext);
  if (!ctx) throw new Error("useLang must be used within LangProvider");
  return ctx;
}
